# Site settings
title: "Jefferson 'shamanime' Venerando"
email: jefferson@shamani.me
description: >
  Words, codes and curses from a software developer.
baseurl: ""
url: "http://shamani.me"
twitter_username: shamanime
github_username:  shamanime

# Build settings
markdown: kramdown

# Custom configuration
timezone: America/Sao_Paulo
permalink: /posts/:title/

